//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishVocabulary
{
    using System;
    using System.Collections.Generic;
    
    public partial class En_to_Vi
    {
        public int id { get; set; }
        public string en { get; set; }
        public string vi { get; set; }
        public Nullable<int> unit { get; set; }
    
        public virtual Unit Unit1 { get; set; }
    }
}
